statemanagement ass component code added
aryaZemo/Zemoso_Training pull request #8
Opened 2023-04-09 13:40 UTC by aryaZemo

I Have added the component related code and functionality code in this, kindly review it.

2023-04-12 09:22 UTC, Sahithi-003 commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/PayBack/PayBack.tsx
> +        text="Pay back Amount"
These text you can get from constants file

2023-04-12 09:22 UTC, Sahithi-003 commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/PayOut/PayOut.tsx
> +        text="Total Payout"
These text you can get from constants file as you did below line 21

2023-04-12 09:24 UTC, Sahithi-003 commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/Slide/Slide.tsx
> +        }}
avoid inline styles all over for any component use styled components

2023-04-12 09:26 UTC, Sahithi-003 requested changes
Please address review comments

2023-04-13 17:34 UTC, aryaZemo commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/PayBack/PayBack.tsx
> +        text="Pay back Amount"
done

2023-04-13 17:36 UTC, aryaZemo commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/PayOut/PayOut.tsx
> +        text="Total Payout"
done

2023-04-13 18:34 UTC, aryaZemo commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/Molecules/Slide/Slide.tsx
> +        }}
done

2023-04-13 18:38 UTC, aryaZemo commented on React/StateManagementAssignment/state-management-assignment/src/Assignment/StyleComponent.tsx
> +  width: 280px;
done

2023-04-14 09:00 UTC, Sahithi-003 approved these changes

2023-04-14 09:05 UTC, merged